---
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
    - id: yamllint
      args: [-c=yamllint.yml]

- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.4.0
  hooks:
    - id: ansible-lint
